name: publish

on:
  push:
    tags:
      - 'v*'
  # Tags created by a workflow using GITHUB_TOKEN do not trigger other workflows
  workflow_run:
    workflows: ["release"]
    types:
      - completed
  workflow_dispatch:

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run ci-build

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name> # TODO
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v6
    - uses: jdx/mise-action@v3
    - run: mise run ci-build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1